CREATE TABLE MEMBERS(
    PKMEMBERID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) 
    IDNUMBER VARCHAR(13) NOT NULL 
    [NAME] VARCHAR(25) NOT NULL,
    SURNAME VARCHAR(50),
    GENDER VARCHAR(20),
    AGE INTEGER,
    CONTACTNUMBER VARCHAR(20),
    JOINDATE DATETIME DEFAULT CURRENT_TIMESTAMP,

    FKMEMBERSHIPTYPE INTEGER NOT NULL,

    FOREIGN KEY (FKMEMBERSHIPTYPE) REFERENCES ENUMMEMBERSHIPTYPE(PKID)

)

CREATE TABLE ENUMMEMBERSHIPTYPE(
    PKID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    CODE VARCHAR(1),
    [DESCRIPTION] VARCHAR(25)
)

-- MEMBERSHIP TYPES:
-- BASIC
-- STANDARD
-- PREMIUM

CREATE TABLE MEMBERFITNESS(
    ID INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    FKMEMBERID INTEGER NOT NULL,
    HEIGHT DECIMAL,
    [WEIGHT] DECIMAL,
    HRmax DECIMAL,
    HRrest DECIMAL,
    OTWOmax DECIMAL,
    FOREIGN KEY (FKMEMBERID) REFERENCES MEMBERS(PKMEMBERID)
)